#!/bin/bash

if [ -f makefile ]
then
	true
else
	echo "xmake: no makefile in the current directory"
	exit 1
fi

make -n -B |
grep -e "^cc" -e "^gcc" |
awk '
	{	# printf("all: '%s'\n", $0);
		if (index($0, ".c") == 0)
		{	next;
		}
		arg = "";
		src = "";
		for (i = 1; i <= NF; i++)
		{	if (index($i, "-D") == 1 \
			||  index($i, "-I") == 1 \
			||  index($i, "-U") == 1)
			{	arg = $i " " arg
			}
			if (index($i, ".c") > 0)
			{	src = $i " " src;
		}	}
		if (length(arg) > 0 && length(src) > 0)
		{	printf("%s%s\n", arg, src);
	}	}
'


exit 0
